name: Content upload request
description: Request your content to be uploaded to the unistore
title: "[Content upload request]: "
body:
  - type: markdown
    attributes:
      value: |
        Please fill the next form with the data of the content you want to upload. This will allow us to review and add your content more quickly.
  - type: input
    id: name
    attributes:
      label: Name
      description: This is how your mod will be labeled
      placeholder: My incredible mod
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe what your mod is about and what it does.
      placeholder: Describe your mod...
    validations:
      required: true
  - type: markdown
    attributes: 
      value: |
        Upload the icon you want for your mod in a comment, please only 48x48 size images. (png, jpeg, jpg)
