name: Content upload request
description: Request your content to be uploaded to the unistore
title: "[Content upload request]: "
body:
  - type: markdown
    attributes:
      value: |
        Please fill the next form with the data of the content you want to upload. This will allow us to review and add your content more quickly.
  - type: input
    id: name
    attributes:
      label: Name
      description: This is how your mod will be labeled.
      placeholder: My incredible mod
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe what your mod is about and what it does.
      placeholder: Describe your mod...
    validations:
      required: true
  - type: dropdown
    id: region
    attributes:
      label: Select the regions that corresponds to your mod (Can select more than one)
      multiple: true
      options:
        - USA
        - EUR
        - JPN
    validations:
      required: true
  - type: textarea
    id: icon
    attributes: 
      label: Icon
      description: This will be your mod icon that will show in the unistore. Only 48x48 icon are accepted.
      placeholder: Attach your icon (png, jpg, jpeg)
    validations:
      required: true
  - type: textarea
    id: mod
    attributes: 
      label: Your content/mod
      description: Attach here the mod file
      placeholder: Attach the file here (zip, 7z, rar)
    validations:
      required: true
